export declare const ERROR_VALUES: readonly [
	'TAP_INVALID_INPUT',
	'TAP_RESOURCE_NOT_FOUND',
	'TAP_TENANT_NOT_FOUND',
	'TAP_SLOT_UNAVAILABLE',
	'TAP_HOLD_NOT_FOUND',
	'TAP_HOLD_EXPIRED',
	'TAP_BOOKING_NOT_FOUND',
	'TAP_UNAUTHENTICATED',
	'TAP_UNAUTHORIZED',
	'TAP_RATE_LIMIT_EXCEEDED',
	'TAP_CONCURRENCY_CONFLICT',
	'TAP_STORAGE_FAILURE',
	'TAP_INTERNAL_ERROR',
	'TAP_INVARIANT_VIOLATION',
	'TAP_QUOTA_EXCEEDED',
];
export declare const BOOKING_STATUSES: readonly ['NONE', 'PENDING', 'PAID'];
export declare const AVAILABILITY_DELTA_KINDS: readonly [
	'HoldPlaced',
	'HoldReleased',
	'HoldExpired',
	'BookingConfirmed',
	'BookingCancelled',
];
export declare const HOLD_RELEASE_REASONS: readonly [
	'DISCONNECTED',
	'SERVER_SHUTDOWN',
	'POLICY_LIMIT',
	'RESOURCE_DISABLED',
];
//# sourceMappingURL=values.d.ts.map
