// Enums and Constants for TAP Protocol

export const ERROR_VALUES = [
	'TAP_INVALID_INPUT',
	'TAP_RESOURCE_NOT_FOUND',
	'TAP_TENANT_NOT_FOUND',
	'TAP_SLOT_UNAVAILABLE',
	'TAP_HOLD_NOT_FOUND',
	'TAP_HOLD_EXPIRED',
	'TAP_BOOKING_NOT_FOUND',
	'TAP_UNAUTHENTICATED',
	'TAP_UNAUTHORIZED',
	'TAP_RATE_LIMIT_EXCEEDED',
	'TAP_CONCURRENCY_CONFLICT',
	'TAP_STORAGE_FAILURE',
	'TAP_INTERNAL_ERROR',
	'TAP_INVARIANT_VIOLATION',
	'TAP_QUOTA_EXCEEDED',
] as const;

export const BOOKING_STATUSES = ['NONE', 'PENDING', 'PAID'] as const;

export const AVAILABILITY_DELTA_KINDS = [
	'HoldPlaced',
	'HoldReleased',
	'HoldExpired',
	'BookingConfirmed',
	'BookingCancelled',
] as const;

export const HOLD_RELEASE_REASONS = [
	'DISCONNECTED',
	'SERVER_SHUTDOWN',
	'POLICY_LIMIT',
	'RESOURCE_DISABLED',
] as const;
