export const API_ROUTES = {
	AVAILABILITY: '/availability',
	BOOK: '/book',
	CANCEL: '/cancel',
	BOOKINGS: '/bookings',
	OFFERS: '/offers',
	OFFERS_CREATE: '/offers/create',
	OFFERS_DELETE: '/offers/delete',
	SESSION: '/session',
	AVAILABILITY_WS: '/availability-ws',
	HOLD_WS: '/hold-ws',
	HEALTH: '/health',
	DISCOVERY: '/.well-known/timebook.json',
	DOCS: '/tap/docs',
	OPENAPI: '/tap/openapi.json',
} as const;
