import type { Metadata } from "next";

// One place for the site's SEO identity and structured-data builders. Titles stay short, descriptions
// land in the 140 to 160 character range, every page gets a canonical, and the JSON-LD nodes share
// stable @id anchors so they form one connected graph across the site.
export const SITE = {
  url: "https://delt.at",
  name: "Δt",
  altNames: ["deltat", "delta t"],
  org: "open-deltat",
  github: "https://github.com/open-deltat",
  deltatRepo: "https://github.com/open-deltat/deltat",
  defaultTitle: "Δt: a database for time",
  description:
    "Δt is a database for time: it stores every booking as a stretch on one line, so finding what is free is one instant lookup. Open, self-hostable, and real-time.",
} as const;

// The brand suffix every page title carries. A layout that defines its own `title` replaces the
// parent's title object INCLUDING its template, which silently drops the suffix for everything
// beneath it; any layout that sets a title must re-state this template alongside it.
export const TITLE_TEMPLATE = "%s · Δt";

export const OG_IMAGE_PATH = "/opengraph-image";

// Page openGraph overrides the layout's, which drops the file-convention image, so every helper sets
// it explicitly. The image itself is generated by app/opengraph-image.tsx.
const OG_IMAGES = [{ url: OG_IMAGE_PATH, width: 1200, height: 630, alt: "Δt: a database for time" }];

function abs(path: string): string {
  return path === "/" ? SITE.url : `${SITE.url}${path}`;
}

// `absoluteTitle` opts a page out of the root layout's "%s · Δt" template. Reserved for the pages
// whose subject IS the brand (the landing, What is Δt, What is TAP), where a suffix would stutter.
export function pageMetadata(opts: {
  title: string;
  description: string;
  path: string;
  ogType?: "website" | "article";
  absoluteTitle?: boolean;
}): Metadata {
  const url = abs(opts.path);
  return {
    title: opts.absoluteTitle ? { absolute: opts.title } : opts.title,
    description: opts.description,
    alternates: { canonical: opts.path },
    openGraph: {
      title: opts.title,
      description: opts.description,
      url,
      siteName: SITE.name,
      type: opts.ogType ?? "website",
      images: OG_IMAGES,
    },
    twitter: {
      card: "summary_large_image",
      title: opts.title,
      description: opts.description,
      images: [OG_IMAGE_PATH],
    },
  };
}

type Ld = Record<string, unknown>;

export function organizationLd(): Ld {
  return {
    "@type": "Organization",
    "@id": `${SITE.url}/#org`,
    name: SITE.org,
    url: SITE.url,
    sameAs: [SITE.github, SITE.deltatRepo],
  };
}

export function websiteLd(): Ld {
  return {
    "@type": "WebSite",
    "@id": `${SITE.url}/#website`,
    url: SITE.url,
    name: SITE.name,
    alternateName: SITE.altNames,
    description: SITE.description,
    inLanguage: "en",
    publisher: { "@id": `${SITE.url}/#org` },
  };
}

export function softwareApplicationLd(): Ld {
  return {
    "@type": "SoftwareApplication",
    "@id": `${SITE.url}/#software`,
    name: SITE.name,
    alternateName: SITE.altNames,
    applicationCategory: "DeveloperApplication",
    operatingSystem: "Linux, macOS, Windows",
    description: SITE.description,
    url: SITE.url,
    softwareHelp: `${SITE.url}/docs`,
    isAccessibleForFree: true,
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    author: { "@id": `${SITE.url}/#org` },
    publisher: { "@id": `${SITE.url}/#org` },
  };
}

export function techArticleLd(opts: { title: string; description: string; path: string }): Ld {
  const url = abs(opts.path);
  return {
    "@type": "TechArticle",
    "@id": `${url}#article`,
    headline: opts.title,
    description: opts.description,
    url,
    inLanguage: "en",
    image: abs(OG_IMAGE_PATH),
    isPartOf: { "@id": `${SITE.url}/#website` },
    about: { "@id": `${SITE.url}/#software` },
    author: { "@id": `${SITE.url}/#org` },
    publisher: { "@id": `${SITE.url}/#org` },
  };
}

export function webPageLd(opts: { title: string; description: string; path: string }): Ld {
  const url = abs(opts.path);
  return {
    "@type": "WebPage",
    "@id": `${url}#webpage`,
    url,
    name: opts.title,
    description: opts.description,
    inLanguage: "en",
    image: abs(OG_IMAGE_PATH),
    isPartOf: { "@id": `${SITE.url}/#website` },
    about: { "@id": `${SITE.url}/#software` },
  };
}

export function breadcrumbLd(items: { name: string; path: string }[]): Ld {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((it, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: it.name,
      item: abs(it.path),
    })),
  };
}
