export const ERROR_VALUES = {
	TAP_INVALID_INPUT: 'TAP_INVALID_INPUT',
	TAP_RESOURCE_NOT_FOUND: 'TAP_RESOURCE_NOT_FOUND',
	TAP_TENANT_NOT_FOUND: 'TAP_TENANT_NOT_FOUND',
	TAP_SLOT_UNAVAILABLE: 'TAP_SLOT_UNAVAILABLE',
	TAP_HOLD_NOT_FOUND: 'TAP_HOLD_NOT_FOUND',
	TAP_HOLD_EXPIRED: 'TAP_HOLD_EXPIRED',
	TAP_BOOKING_NOT_FOUND: 'TAP_BOOKING_NOT_FOUND',
	TAP_RATE_LIMIT_EXCEEDED: 'TAP_RATE_LIMIT_EXCEEDED',
	TAP_QUOTA_EXCEEDED: 'TAP_QUOTA_EXCEEDED',
	TAP_UNAUTHENTICATED: 'TAP_UNAUTHENTICATED',
	TAP_UNAUTHORIZED: 'TAP_UNAUTHORIZED',
	TAP_CONCURRENCY_CONFLICT: 'TAP_CONCURRENCY_CONFLICT',
	TAP_STORAGE_FAILURE: 'TAP_STORAGE_FAILURE',
	TAP_INTERNAL_ERROR: 'TAP_INTERNAL_ERROR',
	TAP_INVARIANT_VIOLATION: 'TAP_INVARIANT_VIOLATION',
} as const;

export type ErrorValue = (typeof ERROR_VALUES)[keyof typeof ERROR_VALUES];
