'use client';

import { Loader2 } from 'lucide-react';
import { Calendar } from '@/components/ui/calendar';
import { format, getClientTimezone } from '@/lib/timezone';
import { TimezoneSelector } from './timezone-selector';

export type DatePickerSectionProps = {
	selectedDate: Date | undefined;
	onSelectDate: (date: Date | undefined) => void;
	onMonthChange: (date: Date) => void;
	availableDays: Set<string>;
	isLoading: boolean;
	timezone: string;
	onTimezoneChange: (timezone: string) => void;
};

export const DatePickerSection = ({
	selectedDate,
	onSelectDate,
	onMonthChange,
	availableDays,
	isLoading,
	timezone,
	onTimezoneChange,
}: DatePickerSectionProps) => {
	return (
		<div className="flex flex-col h-full">
			<div className="p-4 flex-1 flex flex-col">
				<div className="flex items-center justify-between mb-4 px-2">
					<h2 className="text-sm font-semibold tracking-tight">Select Date</h2>
					<div
						className={`transition-opacity duration-300 ${isLoading ? 'opacity-100' : 'opacity-0'}`}
					>
						<Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />
					</div>
				</div>
				<div
					className={`flex-1 flex justify-center transition-opacity duration-300 ${isLoading ? 'opacity-50 pointer-events-none' : 'opacity-100'}`}
				>
					<Calendar
						mode="single"
						selected={selectedDate}
						onSelect={onSelectDate}
						onMonthChange={onMonthChange}
						disabled={(date) => {
							if (date < new Date(new Date().setHours(0, 0, 0, 0))) return true;
							// Use the selected timezone to format the key
							// But wait, availableDays set is currently strings like "2025-11-24"
							// generated by useAvailability using date-fns format (local time of browser running it)
							// If we change timezone, availableDays should be regenerated with that timezone?
							// Yes, useAvailability will handle that.
							// But here, we need to format `date` (which is a local Date object iterated by Calendar)
							// to match the keys in availableDays.
							// Currently Calendar iterates local dates.
							// If we want to support "viewing as another timezone", we have a complexity:
							// React Day Picker works with Date objects (local browser time).
							// If I select "Tokyo", and it's 8pm here but 4am tomorrow there...
							// The calendar grid is still "November 2025" in local time context usually?
							// Actually, if we just use the date string YYYY-MM-DD from the date object,
							// we are checking "Does this date (e.g. Nov 24) have slots in the target timezone?"
							// The slots API returns UTC. useAvailability converts to timezone-specific YYYY-MM-DD.
							// So if we format the calendar's iterated date as YYYY-MM-DD, we match against that set.
							// This implies the calendar "dates" are just abstract dates, not timestamps.
							const dateKey = format(date, 'yyyy-MM-dd');
							return !availableDays.has(dateKey);
						}}
					/>
				</div>
			</div>
			<div className="p-3 border-t bg-muted/5 text-[10px] text-muted-foreground flex items-center justify-between">
				<TimezoneSelector
					timezone={timezone}
					onTimezoneChange={onTimezoneChange}
				/>
				{selectedDate && <span>{format(selectedDate, 'MMM d, yyyy')}</span>}
			</div>
		</div>
	);
};
